-- LoyaltyTree Lending / Loan Management v1
-- Run once in Supabase SQL Editor before deploying the patched backend/frontend.
-- Additive only: does not alter loyalty, Wallet, POS, Order Ahead, or Car Lending tables.

begin;

create table if not exists public.lending_borrowers (
    id bigint generated by default as identity primary key,
    public_id text not null unique,
    business_id bigint not null references public.businesses(id) on delete cascade,
    name text not null,
    phone text,
    email text,
    address text,
    id_number text,
    emergency_contact_name text,
    emergency_contact_phone text,
    photo_url text,
    notes text,
    status text not null default 'active' check (status in ('active','inactive','blocked')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.lending_loans (
    id bigint generated by default as identity primary key,
    public_id text not null unique,
    business_id bigint not null references public.businesses(id) on delete cascade,
    borrower_id bigint not null references public.lending_borrowers(id) on delete restrict,
    branch_id bigint references public.branches(id) on delete set null,
    contract_number text not null,
    principal_amount numeric(14,2) not null check (principal_amount > 0),
    interest_rate numeric(8,4) not null default 0 check (interest_rate >= 0),
    total_payable numeric(14,2) not null check (total_payable > 0),
    installment_amount numeric(14,2) not null check (installment_amount > 0),
    installment_count integer not null check (installment_count > 0 and installment_count <= 1000),
    payment_frequency text not null default 'monthly' check (payment_frequency in ('daily','weekly','biweekly','semimonthly','monthly')),
    release_date date not null,
    first_due_date date not null,
    next_due_date date,
    last_payment_date date,
    balance_remaining numeric(14,2) not null check (balance_remaining >= 0),
    days_past_due integer not null default 0 check (days_past_due >= 0),
    status text not null default 'active' check (status in ('active','overdue','fully_paid','defaulted','cancelled')),
    notes text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (business_id, contract_number)
);

create table if not exists public.lending_installments (
    id bigint generated by default as identity primary key,
    public_id text not null unique,
    business_id bigint not null references public.businesses(id) on delete cascade,
    loan_id bigint not null references public.lending_loans(id) on delete cascade,
    installment_number integer not null check (installment_number > 0),
    due_date date not null,
    amount_due numeric(14,2) not null check (amount_due >= 0),
    amount_paid numeric(14,2) not null default 0 check (amount_paid >= 0),
    paid_date date,
    status text not null default 'pending' check (status in ('pending','partial','paid')),
    performance text not null default 'pending' check (performance in ('pending','on_time','delayed','overdue')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (loan_id, installment_number)
);

create table if not exists public.lending_payments (
    id bigint generated by default as identity primary key,
    public_id text not null unique,
    business_id bigint not null references public.businesses(id) on delete cascade,
    loan_id bigint not null references public.lending_loans(id) on delete cascade,
    borrower_id bigint not null references public.lending_borrowers(id) on delete restrict,
    branch_id bigint references public.branches(id) on delete set null,
    receipt_number text not null,
    amount numeric(14,2) not null check (amount > 0),
    payment_date date not null,
    method text,
    reference_number text,
    notes text,
    timeliness text not null default 'on_time' check (timeliness in ('on_time','delayed')),
    balance_before numeric(14,2) not null,
    balance_after numeric(14,2) not null,
    created_at timestamptz not null default now(),
    unique (business_id, receipt_number)
);

create table if not exists public.lending_documents (
    id bigint generated by default as identity primary key,
    public_id text not null unique,
    business_id bigint not null references public.businesses(id) on delete cascade,
    borrower_id bigint references public.lending_borrowers(id) on delete cascade,
    loan_id bigint references public.lending_loans(id) on delete cascade,
    document_type text not null default 'other',
    title text,
    file_url text,
    storage_path text,
    file_name text,
    mime_type text,
    created_at timestamptz not null default now(),
    check (borrower_id is not null or loan_id is not null),
    check (file_url is not null or storage_path is not null)
);

create index if not exists idx_lending_borrowers_business on public.lending_borrowers(business_id, created_at desc);
create index if not exists idx_lending_borrowers_name on public.lending_borrowers(business_id, name);
create index if not exists idx_lending_loans_business_status on public.lending_loans(business_id, status, next_due_date);
create index if not exists idx_lending_loans_borrower on public.lending_loans(borrower_id, created_at desc);
create index if not exists idx_lending_loans_branch on public.lending_loans(branch_id, created_at desc);
create index if not exists idx_lending_installments_loan_due on public.lending_installments(loan_id, due_date);
create index if not exists idx_lending_installments_business_perf on public.lending_installments(business_id, performance, due_date);
create index if not exists idx_lending_payments_business_date on public.lending_payments(business_id, payment_date desc);
create index if not exists idx_lending_payments_loan on public.lending_payments(loan_id, payment_date desc);
create index if not exists idx_lending_documents_loan on public.lending_documents(loan_id, created_at desc);
create index if not exists idx_lending_documents_borrower on public.lending_documents(borrower_id, created_at desc);

-- Private storage bucket for contracts, IDs, receipts, and other borrower files.
-- No public storage policies are created: the FastAPI service-role connection is
-- the only intended reader/writer and document bytes are proxied through an
-- authenticated Lending endpoint.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
    'lending-documents',
    'lending-documents',
    false,
    10485760,
    array['application/pdf','image/jpeg','image/png','image/webp']::text[]
)
on conflict (id) do update set
    public = false,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

alter table public.lending_borrowers enable row level security;
alter table public.lending_loans enable row level security;
alter table public.lending_installments enable row level security;
alter table public.lending_payments enable row level security;
alter table public.lending_documents enable row level security;

-- LoyaltyTree accesses these tables through the server-side Supabase secret/service-role key.
-- Keep browser roles from talking to financial tables directly.
revoke all on table public.lending_borrowers from anon, authenticated;
revoke all on table public.lending_loans from anon, authenticated;
revoke all on table public.lending_installments from anon, authenticated;
revoke all on table public.lending_payments from anon, authenticated;
revoke all on table public.lending_documents from anon, authenticated;


-- Atomic payment posting. This keeps the payment row, installment allocation,
-- and loan balance in one PostgreSQL transaction so a network/server error
-- cannot leave a half-posted collection.
create or replace function public.record_lending_payment_v1(
    p_business_id bigint,
    p_loan_id bigint,
    p_payment_public_id text,
    p_receipt_number text,
    p_amount numeric,
    p_payment_date date,
    p_method text default null,
    p_reference_number text default null,
    p_notes text default null
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_loan public.lending_loans%rowtype;
    v_inst public.lending_installments%rowtype;
    v_balance_before numeric(14,2);
    v_balance_after numeric(14,2);
    v_remaining numeric(14,2);
    v_outstanding numeric(14,2);
    v_alloc numeric(14,2);
    v_new_paid numeric(14,2);
    v_delayed boolean := false;
    v_payment_id bigint;
begin
    if p_amount is null or p_amount <= 0 then
        raise exception 'Payment amount must be greater than zero';
    end if;

    select * into v_loan
    from public.lending_loans
    where id = p_loan_id and business_id = p_business_id
    for update;

    if not found then
        raise exception 'Loan not found';
    end if;
    if v_loan.status in ('fully_paid','cancelled') then
        raise exception 'Cannot add a payment to a % loan', v_loan.status;
    end if;

    v_balance_before := round(v_loan.balance_remaining, 2);
    if round(p_amount, 2) > v_balance_before then
        raise exception 'Payment exceeds remaining balance';
    end if;

    v_remaining := round(p_amount, 2);

    for v_inst in
        select * from public.lending_installments
        where loan_id = p_loan_id and round(amount_paid,2) < round(amount_due,2)
        order by installment_number
        for update
    loop
        exit when v_remaining <= 0;
        v_outstanding := round(v_inst.amount_due - v_inst.amount_paid, 2);
        v_alloc := least(v_outstanding, v_remaining);
        v_new_paid := round(v_inst.amount_paid + v_alloc, 2);
        v_remaining := round(v_remaining - v_alloc, 2);
        if v_inst.due_date < p_payment_date then
            v_delayed := true;
        end if;

        update public.lending_installments
        set amount_paid = v_new_paid,
            status = case when v_new_paid >= round(v_inst.amount_due,2) then 'paid' else 'partial' end,
            performance = case
                when v_new_paid >= round(v_inst.amount_due,2) then
                    case when v_inst.due_date < p_payment_date then 'delayed' else 'on_time' end
                else
                    case when v_inst.due_date < p_payment_date then 'overdue' else 'pending' end
            end,
            paid_date = case when v_new_paid >= round(v_inst.amount_due,2) then p_payment_date else null end,
            updated_at = now()
        where id = v_inst.id;
    end loop;

    if v_remaining > 0.009 then
        raise exception 'Payment could not be fully allocated to the installment schedule';
    end if;

    v_balance_after := greatest(round(v_balance_before - p_amount, 2), 0);

    insert into public.lending_payments (
        public_id, business_id, loan_id, borrower_id, branch_id,
        receipt_number, amount, payment_date, method, reference_number, notes,
        timeliness, balance_before, balance_after
    ) values (
        p_payment_public_id, p_business_id, p_loan_id, v_loan.borrower_id, v_loan.branch_id,
        p_receipt_number, round(p_amount,2), p_payment_date, p_method, p_reference_number, p_notes,
        case when v_delayed then 'delayed' else 'on_time' end,
        v_balance_before, v_balance_after
    ) returning id into v_payment_id;

    update public.lending_loans
    set balance_remaining = v_balance_after,
        last_payment_date = p_payment_date,
        status = case
            when v_balance_after <= 0.009 then 'fully_paid'
            when status = 'defaulted' then 'defaulted'
            else status
        end,
        updated_at = now()
    where id = p_loan_id;

    return jsonb_build_object(
        'payment_id', v_payment_id,
        'payment_public_id', p_payment_public_id,
        'receipt_number', p_receipt_number,
        'balance_before', v_balance_before,
        'balance_after', v_balance_after,
        'timeliness', case when v_delayed then 'delayed' else 'on_time' end
    );
end;
$$;

revoke all on function public.record_lending_payment_v1(bigint,bigint,text,text,numeric,date,text,text,text) from public, anon, authenticated;
grant execute on function public.record_lending_payment_v1(bigint,bigint,text,text,numeric,date,text,text,text) to service_role;

commit;
