import React from 'react'
import { useNavigate } from 'react-router-dom'

const UPDATED = 'September 12, 2026'

const LEGAL_ENTITY = {
  name: 'LoyaltyTree Information Technology Solutions',
  location: 'Isabela, Philippines',
  phone: '0939 799 2144',
  phoneHref: '+639397992144',
  email: 'theloyaltytree@gmail.com',
}

const DOCUMENTS = {
  privacy: {
    title: 'Privacy Policy',
    intro: 'This Privacy Policy explains how LoyaltyTree collects, uses, stores, shares, protects, and otherwise processes personal data when businesses, staff, customers, members, and website visitors use the LoyaltyTree platform.',
    sections: [
      ['1. Scope and privacy roles', 'This policy applies to LoyaltyTree website visitors, businesses that apply for or use LoyaltyTree, authorized business staff, and customers or members who join a participating business loyalty program. For customer information processed to operate a business-configured loyalty program, the participating business ordinarily determines the customer-facing purpose and rules and generally acts as the personal information controller, while LoyaltyTree generally processes the information on the business’s behalf as a personal information processor. LoyaltyTree may separately act as a personal information controller for processing it determines for its own purposes, including platform accounts, subscription administration, security, fraud prevention, support, legal compliance, and first-party website analytics. Actual roles depend on the specific processing activity and applicable law.'],
      ['2. Information we process', 'Depending on the feature used, we may process business profile and contact details; owner and staff account information; branch and device information; customer identifiers and contact details; loyalty card identifiers; stamps, points, tiers, visits, rewards, memberships, multipasses, gift-card activity and redemptions; transaction and audit records; optional birthday or demographic information; Order Ahead order and pickup information; feedback and support information; payment confirmation and transaction-reference information; and technical, security, device, browser, referral, session and website-usage information. Payment credentials may be handled directly by the applicable payment provider and are not intended to be stored by LoyaltyTree.'],
      ['3. Sensitive personal information and data minimization', 'Philippine law treats age as sensitive personal information. A date of birth can reveal age, so LoyaltyTree treats birthday and age-related processing with heightened safeguards. Businesses should collect birthday, age, health-related, government-issued, or other sensitive information only when necessary for a clearly disclosed and lawful purpose and when the required lawful basis, including specific consent where applicable, exists. LoyaltyTree is not designed as an electronic medical-record system, and businesses must not use general loyalty notes or fields to store diagnoses, medical histories, treatment records, or other unnecessary sensitive health information unless a separate compliant implementation has been expressly agreed.'],
      ['4. Website analytics and approximate location', 'LoyaltyTree uses first-party analytics to measure public website visits, conversions, customer join-page activity, Wallet actions, source/referral information, device type, browser, and similar performance information. Random or pseudonymous visitor and session identifiers may be used for aggregate reporting. An IP address may be processed transiently to estimate an approximate country, region, or city and may be provided to hosting infrastructure or an IP-geolocation service for that limited purpose. LoyaltyTree’s platform analytics are designed not to persist the raw IP address in the analytics database; stored location data is coarse and approximate and is not GPS location.'],
      ['5. Purposes and lawful bases', 'We process information to create and administer accounts and digital loyalty cards; operate Google Wallet and Apple Wallet functionality; record loyalty, reward, membership, tier, multipass and gift-card activity; provide analytics; manage branches and staff; support Order Ahead and configured customer experiences; deliver configured communications; administer subscriptions and payments; provide support; prevent abuse and fraud; maintain security; improve the platform; establish, exercise or defend legal claims; and comply with legal obligations. Processing is based on the lawful ground appropriate to the activity, such as consent, performance of a contract, compliance with a legal obligation, protection of lawful rights and interests, or legitimate interests where permitted. Sensitive personal information is processed only under a basis permitted by Philippine law.'],
      ['6. Participating businesses and customer data', 'A participating business is responsible for collecting and using its customer information lawfully, providing required notices, obtaining consent when required, limiting collection to what is appropriate, keeping customer-facing program rules accurate, restricting staff access, and ensuring that any instruction given to LoyaltyTree is lawful. LoyaltyTree will process business-controlled customer information only as needed to provide the service, comply with lawful instructions and applicable law, maintain security, and protect legal rights.'],
      ['7. Announcements, direct marketing and preferences', 'Businesses may use LoyaltyTree to send announcements, promotions, birthday messages, win-back communications, review requests and other configured communications. Where a communication constitutes direct marketing or otherwise requires consent or another lawful basis, the participating business is responsible for establishing that basis before sending it. Data subjects have the right to object to processing for direct marketing and may contact the participating business or LoyaltyTree, as appropriate to the processing, to exercise that right. LoyaltyTree will honor valid objections for processing it controls and will reasonably assist participating businesses with requests concerning business-controlled data. Operational Wallet updates that are necessary to maintain a card or transaction record may be treated differently from promotional marketing messages.'],
      ['8. Service providers, subprocessors and international processing', 'LoyaltyTree may use hosting, database, cloud storage, image hosting, Wallet, communications, analytics, security, support and payment providers to operate the platform. Those providers may process information in the Philippines or other countries depending on their infrastructure. LoyaltyTree requires appropriate contractual, organizational and technical safeguards where applicable and limits provider access to information reasonably necessary for the service. A current subprocessor or service-provider list may be made available through LoyaltyTree’s official contact channel. LoyaltyTree does not sell personal data as a standalone business product.'],
      ['9. Security and personal-data incidents', 'LoyaltyTree uses reasonable organizational, physical and technical safeguards designed to protect personal data, including access controls, authentication measures, audit records and security monitoring appropriate to the service. No online system can guarantee absolute security. Security incidents and personal-data breaches are assessed and documented, and qualifying breaches will be reported to the National Privacy Commission and affected data subjects within the period required by applicable law. Participating businesses must promptly notify LoyaltyTree of suspected unauthorized access or privacy incidents involving the platform.'],
      ['10. Retention, deletion and account closure', 'Personal data is retained only for as long as needed for the purpose for which it was collected, the duration of the applicable service relationship, legitimate security and fraud-prevention needs, audit and dispute resolution, accounting and contractual requirements, or applicable law. Different categories may have different retention periods. When information is no longer required, LoyaltyTree will delete, anonymize or securely dispose of it in accordance with its retention procedures, subject to lawful preservation requirements. Business customers may request information about the retention schedule applicable to their account and may request export or deletion where legally and technically appropriate.'],
      ['11. Data-subject rights', 'Subject to applicable Philippine law, data subjects may have rights to be informed, access personal data, object to certain processing including direct marketing, correct inaccurate information, request erasure or blocking when warranted, withdraw consent where consent is the basis of processing, obtain data portability where applicable, and lodge a complaint with the National Privacy Commission. Requests concerning information controlled by a participating business may need to be handled by that business, with LoyaltyTree providing reasonable assistance where appropriate.'],
      ['12. Minors and vulnerable data subjects', 'LoyaltyTree is designed primarily for businesses and their customer loyalty programs. A participating business that offers a program to minors or other vulnerable data subjects is responsible for determining the lawful basis, providing age-appropriate notices and obtaining parental, guardian or other consent where required. Businesses should avoid collecting sensitive information that is not necessary to operate the loyalty program.'],
      ['13. Changes to this policy', 'We may update this Privacy Policy when LoyaltyTree’s features, service providers or legal obligations change. Material changes will be reflected by an updated effective date and, where required, additional notice or a renewed consent or opportunity to object will be provided.'],
      ['14. Privacy contact and complaints', 'Privacy questions, data-subject requests and privacy complaints may be sent to theloyaltytree@gmail.com. Requests should identify the relevant participating business, if any, and provide enough information for us to verify and respond to the request without collecting unnecessary data. Data subjects also have the right to lodge a complaint with the National Privacy Commission.']
    ]
  },
  terms: {
    title: 'Terms of Service',
    intro: 'These Terms govern access to and use of LoyaltyTree, including its website, dashboards, digital loyalty cards, Wallet integrations, customer-facing pages, Order Ahead tools, gift-card functionality and related services.',
    sections: [
      ['1. Acceptance and electronic records', 'By creating an account, applying a business, accepting an order or agreement electronically, accessing a dashboard, or otherwise using LoyaltyTree after being given access to these Terms, you agree to these Terms and applicable policies. If you act for a business, you represent that you are authorized to bind or act for that business. Electronic acceptances, records and signatures may be used to evidence agreements to the extent permitted by applicable law.'],
      ['2. Service and feature scope', 'LoyaltyTree provides technology for digital loyalty programs, supported loyalty cards, customer records, staff and branch tools, analytics, announcements, review prompts, subscriptions, tiers, multipasses, gift cards, Order Ahead and integrations such as Google Wallet and Apple Wallet. Features vary by plan and may evolve. Specialized systems, NFC, booking, POS, payment, location, website or other custom integrations may require a separate quotation, statement of work or implementation agreement.'],
      ['3. Participating businesses and customers', 'Participating businesses independently determine their loyalty offers, prices, rewards, products, services, promotions and customer-facing rules. Unless LoyaltyTree expressly agrees otherwise in writing, the participating business—not LoyaltyTree—is the seller or provider of the business’s underlying goods, food, services, rewards, memberships and consumer offers. LoyaltyTree provides the technology used to administer those programs.'],
      ['4. Accounts, staff access and security', 'Users must provide accurate information and protect login credentials, PINs, devices and staff access. Business owners are responsible for assigning and removing staff access and for activity performed through credentials and devices under their control, except to the extent caused by LoyaltyTree. Suspected unauthorized access, credential compromise, fraud or security incidents should be reported promptly.'],
      ['5. Plans, billing, renewal, cancellation and refunds', 'Paid features are provided according to the selected plan, branch tier, billing cycle, checkout information, quotation or written order. Taxes, custom development, implementation, setup items, PR kits, hardware and third-party charges may be separate when disclosed. Renewal, cancellation and refund rules applicable to a purchase will be shown or agreed before payment. Nonpayment may result in limitation, suspension or termination of paid services after reasonable notice where practicable. Nothing in these Terms removes any refund, cancellation or consumer remedy that cannot legally be waived.'],
      ['6. Rewards, points, stamps, subscriptions and gift cards', 'Rewards, discounts, points, stamps, tiers, subscriptions, multipasses, coupons and similar benefits are offered and fulfilled by the participating business unless expressly stated otherwise. The business is responsible for its published loyalty rules and lawful redemption decisions. A paid gift card or stored-value instrument must be configured and honored in accordance with applicable Philippine gift-card law, including rules concerning expiry and unused value. Promotional vouchers, coupons and loyalty rewards may be subject to different legal rules and merchant terms.'],
      ['7. Order Ahead and internet transactions', 'Where a participating business uses LoyaltyTree Order Ahead, the business remains responsible for the accuracy of its menu or catalogue, pricing, availability, taxes, fulfillment, food or product quality, pickup or delivery commitments, statutory receipts or invoices, cancellations, refunds and consumer remedies. LoyaltyTree may provide ordering, status, payment-integration and communication technology but does not become the merchant of the underlying goods or services unless a separate written agreement expressly states otherwise. Users must provide accurate contact and order information and use the ordering service lawfully.'],
      ['8. Promotions and permits', 'A participating business is responsible for determining whether a campaign, contest, limited-period promotion, promise of gain, promotional reward or other activity requires a Department of Trade and Industry sales-promotion permit or other regulatory approval and for obtaining that approval before publication or launch. LoyaltyTree may suspend or remove a promotion that appears unlawful, misleading or unsupported by required approvals.'],
      ['9. Customer communications and direct marketing', 'Announcements, promotions, birthday messages, win-back messages, review requests and similar business communications must be truthful, lawful and supported by the consent or other lawful basis required for the specific processing. Businesses must respect customer objections, withdrawals and communication preferences and may not use LoyaltyTree to send unlawful spam or deceptive marketing.'],
      ['10. Acceptable use', 'Users may not use LoyaltyTree for unlawful, fraudulent, deceptive, abusive, infringing or unauthorized activity; dishonestly manipulate loyalty balances or transaction records; access another account without permission; interfere with security; distribute malicious code; overload or improperly scrape the service; bypass plan or integration restrictions; or collect, upload or use personal data without an appropriate lawful basis.'],
      ['11. Privacy and data protection', 'Use of LoyaltyTree is subject to the Privacy Policy and, where applicable to a participating business, the Business Agreement and any Data Processing Addendum or privacy terms incorporated into the service agreement. Businesses remain responsible for their own customer-facing notices, lawful instructions and compliance obligations.'],
      ['12. Third-party services and Wallet platforms', 'LoyaltyTree may interoperate with third-party hosting, database, storage, Wallet, communications, analytics, security and payment services. Those providers may have separate terms and policies. Integration availability, functionality and approval may change because of third-party rules, device compatibility, network conditions or technical requirements. LoyaltyTree is not responsible for a third party’s independent acts or outages except to the extent responsibility cannot legally be excluded.'],
      ['13. Intellectual property and business content', 'LoyaltyTree retains rights in its platform software, designs, branding, documentation and original materials. Businesses retain rights in their names, logos, product content and other materials they submit and grant LoyaltyTree a non-exclusive permission to host, display, reproduce, transform and transmit those materials as reasonably necessary to provide the service. Businesses represent that they have the rights needed for submitted content.'],
      ['14. Availability, maintenance and changes', 'We aim to provide a reliable service but do not guarantee uninterrupted or error-free operation. Maintenance, third-party outages, internet failures, device incompatibility and security events may affect availability. Features may be improved, modified, replaced or discontinued when reasonably necessary, subject to any specific written commitments in an applicable order or custom-development agreement.'],
      ['15. Suspension, termination and data', 'Access may be restricted or suspended for material breach, security risk, fraud, unlawful activity, nonpayment, abuse or misuse. A user may stop using the service subject to applicable billing and Business Agreement obligations. Data following account closure will be handled according to the Privacy Policy, applicable retention requirements and any business-specific data-processing terms.'],
      ['16. No guaranteed business results and limitation of responsibility', 'LoyaltyTree does not guarantee any particular level of sales, retention, revenue, customer response or growth. LoyaltyTree is not responsible for the quality, safety, legality or fulfillment of a participating business’s underlying goods, services, promotions or rewards. Nothing in these Terms excludes or limits any warranty, statutory right, consumer protection, privacy obligation or liability that cannot lawfully be excluded or limited.'],
      ['17. Complaints, disputes, governing law and contact', 'These Terms are governed by the laws of the Republic of the Philippines, without prejudice to mandatory rights that apply. Complaints may be sent to theloyaltytree@gmail.com and should include enough information to identify the account or transaction at issue. The parties should first attempt in good faith to resolve disputes directly. For internet transactions covered by applicable law, required internal redress and regulatory remedies remain available.']
    ]
  },
  business: {
    title: 'Business Agreement',
    intro: 'This Business Agreement applies to businesses that subscribe to, purchase or deploy LoyaltyTree. It supplements the Terms of Service and defines operational, commercial and data-protection responsibilities between LoyaltyTree and each participating business.',
    sections: [
      ['1. Enrollment, authority and business identity', 'The person enrolling or accepting this Agreement for a business represents that the submitted information is accurate and that they are authorized to establish and manage the LoyaltyTree account and, where applicable, bind the business. The business must provide and keep current its legal or trade name, business address, contact information and other information reasonably required for account verification, consumer disclosures, billing, support and legal compliance.'],
      ['2. Subscription, implementation and scope', 'The business receives the features included in its selected plan, branch tier and agreed add-ons. Specialized integrations, custom development, Order Ahead customization, POS work, hardware, NFC/contactless deployments, PR kits, websites or other non-standard work may require an additional quotation, statement of work, implementation schedule, acceptance criteria or written agreement.'],
      ['3. Fees, renewal, cancellation and refunds', 'The business agrees to pay the fees presented or otherwise agreed for subscriptions and optional services. The applicable billing cycle, renewal method, due date, cancellation process, refund rules, setup fees, hardware costs and custom-development milestones will be stated in checkout, invoice, quotation, order or other written agreement. Plan changes may affect features, usage limits and pricing. Amounts already earned for completed custom work, delivered goods or consumed service periods may be non-refundable to the extent permitted by law and the applicable order.'],
      ['4. Merchant and online-business disclosures', 'The business is responsible for maintaining accurate merchant information used in customer-facing pages, including its business or trade name, branch or business address, contact details, prices, product or service descriptions and other disclosures required for online transactions. LoyaltyTree may display information supplied by the business but is not responsible for inaccurate merchant information provided by the business.'],
      ['5. Loyalty-program rules and customer terms', 'The business determines its customer-facing loyalty offer and is responsible for the accuracy, clarity and legality of reward terms, points, stamps, tiers, subscriptions, memberships, multipasses, promotions, expiration rules, earning rules, announcements and redemption decisions. The business should make material customer program terms reasonably available before or when the customer joins. LoyaltyTree provides the administration technology and does not fulfill the business’s underlying goods, services or rewards unless expressly agreed.'],
      ['6. Paid gift cards and promotional vouchers', 'If the business uses LoyaltyTree to issue a gift card or other stored-value instrument for monetary consideration, the business is responsible for complying with applicable gift-card law, including restrictions on expiry and refusal to honor unused stored value. Promotional vouchers, coupons and loyalty rewards that are legally treated differently must be clearly identified and administered according to the rules applicable to them. The business must not configure a paid stored-value instrument in a manner that unlawfully removes or expires consumer value.'],
      ['7. Sales promotions and regulatory permits', 'The business is responsible for evaluating whether a campaign, promotional reward, contest, limited-period offer, promise of gain or similar activity constitutes a regulated sales promotion and, when required, for obtaining the appropriate DTI or other government permit before publication or launch. The business must provide truthful terms and honor approved promotional mechanics. LoyaltyTree may request proof of approval or suspend a campaign when reasonably necessary for legal or platform protection.'],
      ['8. Customer data, PIC/PIP roles and lawful instructions', 'For customer personal data that the business instructs LoyaltyTree to process to operate the business’s loyalty program, the business ordinarily acts as the personal information controller and LoyaltyTree ordinarily acts as the personal information processor. The business determines the customer-facing purposes, collection and communication rules and must provide required notices, establish lawful bases, obtain consent when required, minimize collection and issue only lawful instructions. LoyaltyTree may act as an independent personal information controller for processing it determines for its own accounts, billing, platform security, fraud prevention, legal compliance and first-party website analytics.'],
      ['9. Data processing, security and incident cooperation', 'Each party will comply with its applicable obligations under Philippine data-protection law. LoyaltyTree will maintain reasonable safeguards and process business-controlled customer information only for the service, lawful instructions, security and legal compliance. The business must maintain appropriate organizational controls, protect credentials, promptly report suspected incidents and cooperate with breach investigation and data-subject requests. Where LoyaltyTree acts as a processor, additional processor obligations, subprocessors, security measures, deletion or return obligations and incident-notification procedures may be set out in a Data Processing Addendum incorporated into the subscription or signed agreement.'],
      ['10. Sensitive information, age data and prohibited medical records', 'The business must not collect sensitive personal information merely because a field is technically available. Age-related or birthday processing must have the specific lawful basis required by Philippine law. LoyaltyTree is not a medical-record or clinical-record system; the business must not use ordinary loyalty, customer-note or transaction fields for diagnoses, medical histories, treatment records or other unnecessary sensitive health information unless a separate compliant implementation has been expressly agreed.'],
      ['11. Staff, access and transaction activity', 'The business decides which owners, managers, cashiers, agents and other personnel receive access and must promptly remove access when no longer authorized. The business is responsible for internal controls around stamps, points, tier progression, redemptions, visits, subscriptions, memberships, multipasses, gift cards and other activity performed by authorized staff. LoyaltyTree may retain audit records for security, support, fraud prevention, accounting and dispute investigation.'],
      ['12. Customer communications and direct marketing', 'The business is responsible for the content and lawful basis of announcements, promotional messages, review requests, birthday messages, win-back messages and other communications it initiates or configures. The business must respect applicable consent requirements and customer rights to object or withdraw consent. Where LoyaltyTree provides preference or opt-out tools, the business must not bypass them. LoyaltyTree may block or suspend communications that appear unlawful, deceptive or abusive.'],
      ['13. Order Ahead and consumer transactions', 'For Order Ahead transactions involving the business’s products or services, the business is the merchant responsible for catalogue and menu accuracy, prices, product descriptions, taxes, fulfillment, preparation, pickup or delivery, consumer communications, statutory invoices or receipts, cancellations, refunds, warranties, food or product safety and other consumer remedies. The business must maintain an accessible complaint channel and cooperate in resolving internet-transaction complaints. LoyaltyTree supplies technology and integrations unless a separate written agreement expressly assigns a different role.'],
      ['14. QR, Wallet, NFC, payments and third-party integrations', 'QR codes, Google Wallet passes, Apple Wallet passes, NFC/contactless functions, POS connections, location services, payments, booking systems, websites and other integrations may depend on compatible devices, third-party services, approvals, network availability and configuration. The business must not misuse credentials, QR codes, APIs or integration mechanisms to bypass security or plan restrictions. Third-party provider requirements may change and can affect availability.'],
      ['15. Business profile, branding and intellectual property', 'The business authorizes LoyaltyTree to use its submitted business name, logo, branch details, contact information, menu or catalogue content and loyalty-program materials as reasonably necessary to create and operate cards, dashboards, QR materials, Wallet passes, Order Ahead pages and agreed promotional or PR materials. The business represents that it has the rights required for those materials. LoyaltyTree retains ownership of its platform, software, system design, reusable code, documentation and pre-existing intellectual property unless a separate custom-development agreement expressly states otherwise.'],
      ['16. Support, changes and service dependencies', 'LoyaltyTree may perform maintenance and release improvements, security changes and feature updates. We will use reasonable efforts to minimize material disruption and support the business according to its plan or separate service arrangement. Third-party outages, Wallet-provider policies, payment-provider availability, device restrictions and internet conditions may affect the service and are outside LoyaltyTree’s complete control.'],
      ['17. Suspension, termination, data return and survival', 'LoyaltyTree may suspend or terminate a business account for material breach, nonpayment, fraud, unlawful processing, security threats, abuse or misuse. Where appropriate, notice and a reasonable opportunity to resolve the issue will be provided. Following termination, data will be retained, exported, returned, anonymized or deleted according to applicable law, the Privacy Policy, the applicable Data Processing Addendum and legitimate security or dispute-resolution needs. Provisions concerning payment, intellectual property, confidentiality, liability, dispute resolution and lawful record retention survive as appropriate.'],
      ['18. Responsibility and B2B liability allocation', 'Each party remains responsible for its own acts, omissions, personnel and legal obligations. The business is responsible for claims arising from its underlying goods, services, loyalty rules, promotions, merchant content, customer communications and unlawful instructions, except to the extent caused by LoyaltyTree. LoyaltyTree remains responsible for its own unlawful acts and contractual breaches. To the maximum extent permitted by law and except for fraud, willful misconduct, confidentiality or data-protection obligations, intellectual-property infringement, unpaid fees, or liabilities that cannot lawfully be limited, LoyaltyTree’s aggregate contractual liability to the business will not exceed the fees paid by that business to LoyaltyTree during the twelve months immediately preceding the event giving rise to the claim.'],
      ['19. Governing documents and order of precedence', 'This Agreement is governed by the laws of the Republic of the Philippines. The Terms of Service, Privacy Policy, selected plan or order, applicable Data Processing Addendum, and any signed quotation, statement of work or specialized agreement incorporated by reference form the applicable agreement. A specialized written agreement controls for its specific project to the extent it expressly conflicts with this general Agreement.'],
      ['20. Notices, complaints and contact', 'Business agreement, billing, support, privacy and account questions may be sent to theloyaltytree@gmail.com through the official LoyaltyTree contact channels. Formal notices should identify the business and relevant account or transaction. Nothing in this Agreement prevents either party from using regulatory, judicial or other remedies that cannot legally be waived.']
    ]
  }
}

export default function LegalPage({ type='privacy' }) {
  const navigate=useNavigate()
  const doc=DOCUMENTS[type] || DOCUMENTS.privacy
  return <div style={s.page}>
    <header style={s.header}><button onClick={()=>navigate('/')} style={s.brand}>LoyaltyTree</button><button onClick={()=>navigate('/')} style={s.back}>← Back to Home</button></header>
    <main style={s.main}>
      <div style={s.eyebrow}>LEGAL</div><h1 style={s.h1}>{doc.title}</h1><div style={s.updated}>Effective / last updated: {UPDATED}</div><p style={s.intro}>{doc.intro}</p>
      <div style={s.notice}>These documents describe LoyaltyTree’s platform rules and privacy practices. They are not a substitute for legal advice regarding a business’s particular circumstances.</div>
      <div style={s.identityCard}>
        <div style={s.identityLabel}>PLATFORM OPERATOR</div>
        <div style={s.identityName}>{LEGAL_ENTITY.name}</div>
        <div style={s.identityMeta}>{LEGAL_ENTITY.location}</div>
        <div style={s.identityContacts}>
          <a href={`tel:${LEGAL_ENTITY.phoneHref}`} style={s.identityLink}>{LEGAL_ENTITY.phone}</a>
          <a href={`mailto:${LEGAL_ENTITY.email}`} style={s.identityLink}>{LEGAL_ENTITY.email}</a>
        </div>
      </div>
      <article style={s.card}>{doc.sections.map(([h,p])=><section key={h} style={s.section}><h2 style={s.h2}>{h}</h2><p style={s.p}>{p}</p></section>)}</article>
      <nav style={s.nav}><button onClick={()=>navigate('/privacy')} style={s.link}>Privacy Policy</button><button onClick={()=>navigate('/terms')} style={s.link}>Terms of Service</button><button onClick={()=>navigate('/business-agreement')} style={s.link}>Business Agreement</button></nav>
    </main>
    <footer style={s.footer}>
      <strong>{LEGAL_ENTITY.name}</strong> · {LEGAL_ENTITY.location} · {LEGAL_ENTITY.phone} · {LEGAL_ENTITY.email}<br/>
      © 2026 LoyaltyTree. All rights reserved.
    </footer>
  </div>
}
const s={
 page:{minHeight:'100vh',background:'#f7fbf9',color:'#0f172a',fontFamily:"-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif"},
 header:{minHeight:72,padding:'0 6%',display:'flex',alignItems:'center',justifyContent:'space-between',gap:16,background:'#fff',borderBottom:'1px solid #e2e8f0',position:'sticky',top:0,zIndex:20},
 brand:{border:0,background:'transparent',color:'#0f766e',fontWeight:900,fontSize:22,cursor:'pointer',padding:0},back:{border:'1px solid #dbe5e1',background:'#fff',color:'#0f766e',borderRadius:10,padding:'9px 13px',fontWeight:800,cursor:'pointer'},
 main:{width:'min(900px,88%)',margin:'0 auto',padding:'64px 0 52px'},eyebrow:{color:'#0f766e',fontWeight:900,letterSpacing:'0.18em',fontSize:12,marginBottom:12},
 h1:{margin:'0 0 8px',fontSize:'clamp(36px,6vw,60px)',lineHeight:1.05,letterSpacing:'-0.035em'},updated:{margin:'0 0 24px',color:'#64748b',fontSize:13},
 intro:{margin:'0 0 26px',color:'#475569',fontSize:18,lineHeight:1.75,maxWidth:800},notice:{background:'#ecfdf5',border:'1px solid #bbf7d0',color:'#166534',padding:'15px 17px',borderRadius:12,fontSize:13,lineHeight:1.6,marginBottom:22},identityCard:{background:'#fff',border:'1px solid #cfe3dc',borderRadius:14,padding:'16px 18px',margin:'0 0 22px',boxShadow:'0 8px 22px rgba(15,23,42,.04)'},identityLabel:{fontSize:10,fontWeight:900,letterSpacing:'.14em',color:'#0f766e',marginBottom:5},identityName:{fontSize:16,fontWeight:900,color:'#0f172a'},identityMeta:{fontSize:13,color:'#64748b',marginTop:3},identityContacts:{display:'flex',flexWrap:'wrap',gap:12,marginTop:9},identityLink:{color:'#0f766e',fontSize:13,fontWeight:800,textDecoration:'none'},
 card:{background:'#fff',border:'1px solid #e2e8f0',borderRadius:18,padding:'clamp(22px,5vw,46px)',boxShadow:'0 14px 40px rgba(15,23,42,.05)'},section:{padding:'0 0 26px',margin:'0 0 26px',borderBottom:'1px solid #eef2f7'},
 h2:{margin:'0 0 12px',fontSize:20,lineHeight:1.3},p:{margin:0,color:'#475569',lineHeight:1.75,fontSize:15},nav:{display:'flex',flexWrap:'wrap',gap:10,marginTop:24},
 link:{border:'1px solid #cfe3dc',background:'#fff',color:'#0f766e',borderRadius:10,padding:'10px 13px',fontWeight:800,cursor:'pointer'},footer:{textAlign:'center',padding:'24px 6%',background:'#073f36',color:'#a7d8c9',fontSize:12}
}
