import React, { useEffect, useState } from 'react'

function money(v){return `₱${Number(v||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`}
function PartnerDashboard({API_BASE,user,onLogout}){
  const [data,setData]=useState(null); const [error,setError]=useState('')
  const load=async()=>{try{const r=await fetch(`${API_BASE}/api/v1/partner/dashboard`,{headers:{Authorization:`Bearer ${user?.token}`}}); if(r.status===401||r.status===403){onLogout();return} const d=await r.json(); if(!r.ok)throw new Error(d.detail||'Could not load partner dashboard');setData(d)}catch(e){setError(e.message)}}
  useEffect(()=>{load()},[user?.token])
  if(!data)return <div style={s.page}><div style={s.card}>{error||'Loading partner dashboard…'}</div></div>
  const {partner,stats,businesses,commissions}=data
  return <div style={s.page}>
    <header style={s.header}><div><div style={s.kicker}>{partner.partner_type==='region'?'REGION PARTNER':'CITY PARTNER'}</div><h1 style={s.h1}>{partner.name}</h1><div style={s.sub}>{partner.city?`${partner.city}, `:''}{partner.region} · Code <b>{partner.partner_code}</b></div></div><button style={s.logout} onClick={onLogout}>Log out</button></header>
    <main style={s.main}>
      <div style={s.stats}>{[['Businesses',stats.businesses],['Active',stats.active_businesses],['Pending setup',stats.pending_businesses],['Commission earned',money(stats.commission_earned)],['Unpaid commission',money(stats.commission_unpaid)]].map(([a,b])=><div style={s.stat} key={a}><div style={s.statLabel}>{a}</div><div style={s.statVal}>{b}</div></div>)}</div>
      <section style={s.card}><h2 style={s.h2}>Assigned businesses</h2><p style={s.note}>Operational setup view only. Customer personal data and sensitive transaction details are not available to partner accounts.</p><div style={s.grid}>{businesses.map(b=><div style={s.biz} key={b.public_id}><b>{b.name}</b><span>{b.address||'Address not set'}</span><span>{b.plan} · {b.status}</span><span>QR kit: {b.setup_kit_status||'Not requested'}</span></div>)}{!businesses.length&&<div style={s.empty}>No businesses assigned yet.</div>}</div></section>
      <section style={s.card}><h2 style={s.h2}>Commission activity</h2><div style={{overflowX:'auto'}}><table style={s.table}><thead><tr><th>Business</th><th>Gross</th><th>Commission</th><th>Status</th><th>Date</th></tr></thead><tbody>{commissions.map(c=><tr key={c.public_id}><td>{c.business_name}</td><td>{money(c.gross_amount)}</td><td><b>{money(c.commission_amount)}</b></td><td>{c.status}</td><td>{c.earned_at?new Date(c.earned_at).toLocaleDateString():''}</td></tr>)}</tbody></table></div>{!commissions.length&&<div style={s.empty}>No commission activity yet.</div>}</section>
    </main>
  </div>
}
const s={page:{minHeight:'100vh',background:'#f8fafc',fontFamily:'-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif',color:'#0f172a'},header:{background:'#0f766e',color:'white',padding:'22px clamp(18px,5vw,60px)',display:'flex',justifyContent:'space-between',gap:20,alignItems:'center'},kicker:{fontSize:11,fontWeight:800,letterSpacing:1.4,opacity:.8},h1:{margin:'4px 0',fontSize:28},sub:{fontSize:13,opacity:.9},logout:{border:'1px solid rgba(255,255,255,.5)',background:'transparent',color:'white',borderRadius:9,padding:'9px 14px',fontWeight:700},main:{maxWidth:1200,margin:'0 auto',padding:'24px clamp(14px,4vw,34px)'},stats:{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:12,marginBottom:18},stat:{background:'white',border:'1px solid #e2e8f0',borderRadius:14,padding:16},statLabel:{fontSize:12,color:'#64748b',fontWeight:700},statVal:{fontSize:24,fontWeight:850,marginTop:6},card:{background:'white',border:'1px solid #e2e8f0',borderRadius:16,padding:18,marginBottom:18},h2:{margin:'0 0 6px',fontSize:18},note:{margin:'0 0 15px',fontSize:12,color:'#64748b'},grid:{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:10},biz:{display:'flex',flexDirection:'column',gap:5,padding:13,border:'1px solid #e2e8f0',borderRadius:11,fontSize:12,color:'#64748b'},empty:{padding:18,color:'#94a3b8',textAlign:'center'},table:{width:'100%',borderCollapse:'collapse',fontSize:13}}
export default PartnerDashboard
